# Generated by Django 5.1.6 on 2025-03-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_numbers',
            field=models.ManyToManyField(blank=True, related_name='orders', to='tracking.trackingnumber', verbose_name='Трек-номера'),
        ),
    ]
