# Generated by Django 5.1.6 on 2025-03-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код компании')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API ключ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Транспортная компания',
                'verbose_name_plural': 'Транспортные компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('shipped', 'Отправлено'), ('in_transit', 'В пути'), ('customs', 'На таможне'), ('arrived', 'Прибыло в страну назначения'), ('delivered', 'Доставлено'), ('returned', 'Возвращено'), ('lost', 'Утеряно'), ('unknown', 'Статус неизвестен')], max_length=20, verbose_name='Статус')),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Ожидает отправки'), ('shipped', 'Отправлено'), ('in_transit', 'В пути'), ('customs', 'На таможне'), ('arrived', 'Прибыло в страну назначения'), ('delivered', 'Доставлено'), ('returned', 'Возвращено'), ('lost', 'Утеряно'), ('unknown', 'Статус неизвестен')], max_length=20, null=True, verbose_name='Предыдущий статус')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'История трекинга',
                'verbose_name_plural': 'История трекинга',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrackingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Уведомление о трекинге',
                'verbose_name_plural': 'Уведомления о трекинге',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Трек-номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('current_status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('shipped', 'Отправлено'), ('in_transit', 'В пути'), ('customs', 'На таможне'), ('arrived', 'Прибыло в страну назначения'), ('delivered', 'Доставлено'), ('returned', 'Возвращено'), ('lost', 'Утеряно'), ('unknown', 'Статус неизвестен')], default='pending', max_length=20, verbose_name='Текущий статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('shipped_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемая дата доставки')),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('is_problematic', models.BooleanField(default=False, verbose_name='Проблемная доставка')),
            ],
            options={
                'verbose_name': 'Трек-номер',
                'verbose_name_plural': 'Трек-номера',
                'ordering': ['-created_at'],
            },
        ),
    ]
