# Generated by Django 5.1.6 on 2025-03-06 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='trackingnumber',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_numbers', to='tracking.trackingcompany', verbose_name='Транспортная компания'),
        ),
        migrations.AddField(
            model_name='trackingnumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_numbers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='trackingnotification',
            name='tracking_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tracking.trackingnumber', verbose_name='Трек-номер'),
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='tracking_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracking.trackingnumber', verbose_name='Трек-номер'),
        ),
    ]
