# Generated by Django 5.1.6 on 2025-03-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название дашборда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('layout', models.JSONField(blank=True, null=True, verbose_name='Макет')),
                ('configuration', models.JSONField(blank=True, null=True, verbose_name='Конфигурация')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дашборд',
                'verbose_name_plural': 'Дашборды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отчета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Параметры')),
                ('date_range_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало периода')),
                ('date_range_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец периода')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл отчета')),
                ('file_format', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10, verbose_name='Формат файла')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('report_type', models.CharField(choices=[('inventory', 'Отчет по складу'), ('orders', 'Отчет по заказам'), ('tracking', 'Отчет по трекингу'), ('finance', 'Финансовый отчет'), ('custom', 'Пользовательский отчет')], max_length=20, verbose_name='Тип отчета')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='report_templates/', verbose_name='Файл шаблона')),
                ('default_format', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], default='excel', max_length=10, verbose_name='Формат по умолчанию')),
                ('query', models.TextField(blank=True, null=True, verbose_name='SQL-запрос')),
                ('configuration', models.JSONField(blank=True, null=True, verbose_name='Конфигурация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально')], max_length=20, verbose_name='Частота')),
                ('day_of_week', models.IntegerField(blank=True, null=True, verbose_name='День недели (1-7)')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='День месяца')),
                ('time_of_day', models.TimeField(verbose_name='Время генерации')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Параметры')),
                ('file_format', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10, verbose_name='Формат файла')),
                ('send_email', models.BooleanField(default=True, verbose_name='Отправлять по email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
            ],
            options={
                'verbose_name': 'Запланированный отчет',
                'verbose_name_plural': 'Запланированные отчеты',
                'ordering': ['name'],
            },
        ),
    ]
